naming:
  ClassNaming:
    excludes: &testFiles # Allows ticks-named nested test and spec suites.
      - "**/*Test.kt"
      - "**/*Spec.kt"
  MatchingDeclarationName:
    excludes: *testFiles # Allows ticks-named top-level test and spec suites.
  FunctionNaming:
    ignoreAnnotated: 'Composable'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

style:
  UnusedPrivateMember:
    allowedNames: '(_|ignored|expected|serialVersionUID|about|ABOUT)'
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '3'
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    maxLineLength: 100
    excludeCommentStatements: true
  ForbiddenComment:
    allowedPatterns: 'TODO:'

complexity:
  TooManyFunctions:
    excludes:
      - '**/*Exts.kt'
      - '**/*Extensions.kt'
      - '**/*View.kt'
      - '**/*Projection.kt'
      - '**/*Test.kt'
      - '**/*Spec.kt'
  LongMethod:
    excludes: *testFiles # Allows long names for test and spec methods.
  LongParameterList:
    functionThreshold: "10"
    ignoreDefaultParameters: true
