naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

style:
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '3'
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    maxLineLength: 100
    excludeCommentStatements: true
  ForbiddenComment:
    allowedPatterns: 'TODO:'

complexity:
  TooManyFunctions:
    excludes:
      - '**/*Exts.kt'
      - '**/*Extensions.kt'
      - '**/*View.kt'
      - '**/*Projection.kt'
      - '**/*Test.kt'
      - '**/*Spec.kt'
  LongParameterList:
    functionThreshold: "10"
